### ISSUE TITLE
Support arbitrary object path prefix

### ISSUE THREAD

**Issue by mfischer-zd** [pshima/consul-snapshot#11]
We'd like to be able to specify an arbitrary prefix to each uploaded object.  

Hostname would ordinarily be the obvious choice, but not all systems have useful names, especially AWS instances.  Another alternative one might choose would be the Consul datacenter name -- after all, that's the scope of the backup.

**Comment by pshima** [comment]
:+1:  I can probably tackle this in the next few days.
