### ISSUE TITLE
Implement restore ACLs and PQs

### ISSUE THREAD

**Issue by richard-mauri** [pshima/consul-snapshot#16]
The restore.go is stubbed out and not listed a a TODO

**Comment by pshima** [comment]
Thanks!

https://github.com/pshima/consul-snapshot/commit/c8a984f6b8595bbc4aeef9b46e5bc6721282c44c

**Comment by richard-mauri** [comment]
I see that Consul 0.7.1 is now GA with backup/restore as a new feature.
I'm wondering what lies ahead for this project.
Should it be refactored to call the new endpoints with the value add being the nomad deployable daemon or ?

**Comment by pshima** [comment]
That is a great new feature in consul, but it looks like you still need a way to get the backup in to S3 or elsewhere and this also adds monitoring to it.

Eventually I would guess that consul will support all of this out of the box.
