### ISSUE TITLE
What do you mean by "Add metrics"?

### ISSUE THREAD

**Issue by darron** [pshima/consul-snapshot#2]
If it's anything like some of the other Hashicorp projects I would assume that you'd want to use [go-metrics](https://github.com/armon/go-metrics)

Do you have any idea what operations you want covered by metrics? If not - I'm sure I can figure some out.

Just looking for something I could conceivably contribute for a project that looks like it could work in our environment as well.

Let me know and I'll see what I can do!

**Comment by pshima** [comment]
@darron sorry I totally missed your issue here!

I was thinking 
- Age of last backup (to alarm based on graph instead of consul alert)
- Errors
- Size of backup
- Number of keys backed up

**Comment by pshima** [comment]
Going to close this issue as these will likely be clarified if the feature develops.
