### ISSUE TITLE
Install no longer working on Ubuntu 16.04

### ISSUE THREAD

**Issue by snoremac** [pshima/consul-snapshot#22]
Hi,

Commit https://github.com/pshima/consul-snapshot/commit/5a01c07c214e6d031eb4352096222ba3f7cbd98d seems to introduce a change that depends on Go 1.7, which rules out vanilla Ubuntu 16.04 LTS.

Is that deliberate?  Is hunting down a golang 1.7 PPA the only option now?

thanks,

Cam

**Comment by pshima** [comment]
Can you share with me the error you are getting?

**Comment by snoremac** [comment]
Sorry my bad.

`
root@18a8ae5c91f4:/# export GOPATH="/usr/local/go" && go get github.com/pshima/consul-snapshot
package context: unrecognized import path "context" (import path does not begin with hostname)
`

**Comment by pshima** [comment]
Ok thanks I will try and repro this afternoon. 

On Aug 15, 2017, at 8:39 AM, snoremac <notifications@github.com> wrote:

Sorry my bad.

root@18a8ae5c91f4:/# export GOPATH="/usr/local/go" && go get github.com/pshima/consul-snapshot package context: unrecognized import path "context" (import path does not begin with hostname)

**Comment by pshima** [comment]
Can you give it another try?

Snagged the 16.04 container, `apt-get install golang-go git` and then your above with success.

Added travis builds for 1.6 and 1.7 which are still failing but suspect that is something in my make file that I need to fix.

**Comment by pshima** [comment]
So the bad news is that consul requires 1.8 which is required by consul-snapshot and it is the consul pull that is failing.

Honest question though - why is the reason for building instead of using one of the pre built binaries?

**Comment by snoremac** [comment]
Yeah fair question.  We've had some ansible automation that's been installing it this way for a while, that's all.

So I guess we'll change our playbook to use the binary install method.

Thanks.
