### ISSUE TITLE
What are the mandatory environment variables

### ISSUE THREAD

**Issue by ssala7** [pshima/consul-snapshot#23]
I have created a docker container and exporting the below variables
export S3BUCKET=s3://mybucketname/myfolder
export S3Region=ap-southeast-1
export BACKUPINTERVAL=60
export CRYPTO_PASSWORD=mypassword
export SNAPSHOT_TMP_DIR=/tmp
export CONSUL_SNAPSHOT_UPLOAD_PREFIX=consul01
export CONSUL_HTTP_ADDR=0.0.0.0:8500
export CONSUL_HTTP_TOKEN=nil
export CONSUL_HTTP_AUTH=nil
export CONSUL_HTTP_SSL=nil
export CONSUL_HTTP_SSL_VERIFY=nil

```
/go # consul-snapshot backup
[INFO] v0.2.4: Starting Consul Snapshot
2017/08/31 07:59:55 [ERR] Required env var missing, exiting
```

**Comment by pshima** [comment]
Hi @ssala7 here is the code:
https://github.com/pshima/consul-snapshot/blob/8f521733535e73ff476fa87d732d4ccc4ca8e173/config/config.go#L96

IIRC you just need to change S3Region to S3REGION
