### ISSUE TITLE
consul backup  - running once

### ISSUE THREAD

**Issue by rikibarel** [pshima/consul-snapshot#6]
Hi,
Can you please add adhoc backup , run backup once ?
Thanks
Riki

**Comment by pshima** [comment]
Hi @rikibarel, 

I think that would be a good feature!  I will think about adding that in the future.

**Comment by rikibarel** [comment]
thanks !!!

**Comment by pshima** [comment]
Added to the Todos list here: https://github.com/pshima/consul-snapshot/blob/master/README.md#todos

**Comment by capone212** [comment]
Hi, I need adhoc backup too. And it will be good to have several options for backup destination, other than S3
